-- Jumat Scheduler NAIST - seed data
-- Roster imported from 'List of Khatib and Imam' sheet, statuses as of 2026-09-17.
-- 2025 schedule imported as read-only history from the original spreadsheet.

INSERT INTO people (name, country, role, status, note) VALUES
  ('Rifqi', 'Indonesia', 'khatib', 'active', 'Expected to leave NAIST around September 2029'),
  ('Trisna', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around March 2026'),
  ('Kamal', 'Indonesia', 'khatib', 'active', NULL),
  ('Akmal', 'Malaysia', 'khatib', 'active', NULL),
  ('Abdul Rosyid', 'Indonesia', 'khatib', 'active', NULL),
  ('Rizki Pratama', 'Indonesia', 'khatib', 'active', NULL),
  ('Furqon', 'Indonesia', 'khatib', 'active', NULL),
  ('Alqaaf', 'Indonesia', 'khatib', 'active', NULL),
  ('Imran', 'Bangladesh', 'khatib', 'active', NULL),
  ('Shihab', 'Bangladesh', 'khatib', 'active', 'Expected to leave NAIST around September 2027'),
  ('Hanan', 'Indonesia', 'khatib', 'active', NULL),
  ('Nazmul', 'Bangladesh', 'khatib', 'active', NULL),
  ('Dian Amir', 'Indonesia', 'khatib', 'active', NULL),
  ('Bagus Tris', 'Indonesia', 'khatib', 'active', NULL),
  ('Firoz', 'Bangladesh', 'khatib', 'active', NULL),
  ('Rasyid', 'Indonesia', 'khatib', 'active', 'Expected to leave NAIST around September 2027'),
  ('Ismail Arai', 'Japan', 'khatib', 'active', NULL),
  ('Musa', NULL, 'khatib', 'active', NULL),
  ('Borhan Rownak', NULL, 'khatib', 'active', NULL),
  ('Hanief', 'Indonesia', 'khatib', 'active', NULL),
  ('Aditya', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around September 2025'),
  ('Mahir Chowhury', 'Bangladesh', 'khatib', 'inactive', 'Left NAIST around September 2025'),
  ('Ridho Priyo', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around September 2025'),
  ('Sapto', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around September 2025'),
  ('Hendrick Sedayu', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around September 2025'),
  ('Nanang Adrianto', 'Indonesia', 'khatib', 'inactive', 'Left NAIST around September 2026'),
  ('Sihabul Islam', NULL, 'imam', 'active', NULL),
  ('Mushaffa Rasyid', 'Indonesia', 'imam', 'active', NULL);

INSERT INTO fridays (date, primary_khatib_name, secondary_khatib_name, venue, info, is_history) VALUES
  ('2025-01-03', 'Mahir', 'Rizky', 'Lounge Dorm 1', 'TBA', 1),
  ('2025-01-10', 'Rizky', 'Ridho Priyo', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-01-17', 'Ridho Priyo', 'M Hendrick Sedayu', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-01-24', 'M Hendrick Sedayu', 'Sihabul Islam', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-01-31', 'Sihabul Islam', 'Hanief', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-02-07', 'Rasyid', NULL, 'Assembly Room - SENTAN', NULL, 1),
  ('2025-02-14', 'Hanief', 'Rizki Pratama', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-02-21', 'Rizky Pratama', 'Mohammad Hafiz Hersyah', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-02-28', 'Mohammad Hafiz Hersyah', 'Wahid Senjoh', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-03-07', 'Wahid Senjoh', 'Kamal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-03-14', 'Kamal', 'Aditya', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-03-21', 'Aditya', 'Musa', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-03-28', 'Musa', 'Akmal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-04-04', 'Akmal', 'Sihabul Imam', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-04-11', 'Sihabul Imam', 'Sapto Mukmin', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-04-18', 'Sapto Mukmin', 'Ridho Priyo', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-04-25', 'Ridho Priyo', 'Alqaaf', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-05-02', 'Alqaaf', 'Trisna', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-05-09', 'Trisna', 'Kamal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-05-16', 'Mushaffa', 'Aditya', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-05-23', 'Aditya', 'Hanief', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-05-30', 'Rasyid', 'Mahir Chowhury', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-06-06', 'Mahir Chowhury', 'M Hendrick Sedayu', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-06-13', 'M Hendrick Sedayu', 'Nanang Adrianto', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-06-20', 'Nanang Adrianto', 'Sihabul Islam', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-06-27', 'Sihabul Islam', 'Rifqi', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-07-04', 'Rifqi', 'Rizky Pratama', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-07-11', 'Rizky Pratama', 'Ismail Arai', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-07-18', 'Ismail Arai', 'Musa', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-07-25', 'Sihabul Islam', 'Trisna', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-08-01', 'Trisna', 'Sapto', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-08-08', 'Sapto', 'Ismail Arai', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-08-15', 'Ismail Arai', 'Kamal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-08-22', 'Kamal', 'Furqan', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-08-29', 'Furqan', 'Akmal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-09-05', 'Akmal', 'Imran', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-09-12', 'Imran', 'Shihab', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-09-19', 'Shihab', 'Borhan Rownak', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-09-26', 'Borhan Rownak', 'Hanan', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-10-03', 'Hanan', 'Dian Amir', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-10-10', 'Dian Amir', 'Bagus', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-10-17', 'Bagus', 'Firoz', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-10-24', 'Firoz', 'Rasyid', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-10-31', 'Rasyid', 'Hanief', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-11-07', 'Hanief', 'Aditya', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-11-14', 'Aditya', 'Alqaaf', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-11-21', 'Alqaaf', 'Rifqi', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-11-28', 'Rifqi', 'Kamal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-12-05', 'Kamal', 'Akmal', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-12-12', 'Akmal', 'Rizky', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-12-19', 'Rizky', 'Abdul Rosyid', 'Assembly Room - SENTAN', NULL, 1),
  ('2025-12-26', 'Abdul Rosyid', 'Furqan', 'Assembly Room - SENTAN', NULL, 1);
